version: "3.9"

services:
    # es:
    #     image: elasticsearch:7.17.9
    #     environment:
    #         - discovery.type=single-node
    #     ports:
    #         - "9200:9200"
    #     networks:
    #         - authors-api

    krakenlabs_certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - krakenlabs-api


    krakenlabs_api:
        container_name: krakenlabs_api
        build:
            context: .
            dockerfile: ./docker/dev/django/Dockerfile
        command: /start
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - ./.envs/.dev/.django
            - ./.envs/.dev/.postgres
        depends_on:
            - krakenlabs_postgres
            # - mailhog
            # - redis
            # - es
        networks:
            - krakenlabs-api

    krakenlabs_postgres:
        container_name: krakenlabs_postgres
        build:
            context: .
            dockerfile: ./docker/dev/postgres/Dockerfile
        volumes:
            - dev_postgres_data:/var/lib/postgresql/data
            - dev_postgres_data_backups:/backups
        env_file:
            - ./.envs/.dev/.postgres
        networks:
            - krakenlabs-api

    # mailhs-api

    # redis:
    #     image: redis:7-alpine
    #     networks:
    #         - krakenlabs-api

    # celery_worker:
    #     build:
    #         context: .
    #         dockerfile: ./docker/dev/django/Dockerfile
    #     command: /start-celeryworker
    #     volumes:
    #         - .:/app
    #     env_file:
    #         - ./.envs/.dev/.django
    #         - ./.envs/.dev/.postgres
    #     depends_on:
    #         - redis
    #         - postgres
    #         - mailhog
    #     networks:
    #         - krakenlabs-api

    # flower:
    #     build:
    #         context: .
    #         dockerfile: ./docker/dev/django/Dockerfile
    #     command: /start-flower
    #     volumes:
    #         - flower_data:/data
    #     env_file:
    #         - ./.envs/.dev/.django
    #         - ./.envs/.dev/.postgres
    #     ports:
    #         - "5555:5555"
    #     depends_on:
    #         - redis
    #         - postgres
    #     networks:
    #         - krakenlabs-api

    krakenlabs_nginx:
        container_name: krakenlabs_nginx
        restart: always
        depends_on:
            - krakenlabs_api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
            - ./certbot/www/:/var/www/certbot/:ro
        build:
            context: ./docker/dev/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        networks:
            - krakenlabs-api

networks:
    krakenlabs-api:
        driver: bridge

volumes:
    static_volume:
        name: krakenlabs_static_volume
    media_volume:
        name: krakenlabs_media_volume
    dev_postgres_data:
        name: krakenlabs_postgres_data
    dev_postgres_data_backups:
        name: krakenlabs_postgres_data_backups
    flower_data:
        name: krakenlabs_flower_data